<?php

use Illuminate\Database\Seeder;

class DistrictsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->insert([
        	[ 'name' => 'Amansie East', 'region_id' => 1],
			[ 'name' => 'Amansie Central', 'region_id' => 1],
			[ 'name' => 'Atwima Nwabiagya', 'region_id' => 1],
			[ 'name' => 'Ejusu Juaben', 'region_id' => 1],
			[ 'name' => 'Bosumtwe-Atwima-Kwanwoma', 'region_id' => 1],
			[ 'name' => 'Kwabre', 'region_id' => 1],
			[ 'name' => 'Offinso', 'region_id' => 1],
			[ 'name' => 'Adansi North', 'region_id' => 1],
			[ 'name' => 'Obuasi (Adansi West)', 'region_id' => 1],
			[ 'name' => 'Adansi South (East)', 'region_id' => 1],
			[ 'name' => 'Asante Akim North', 'region_id' => 1],
			[ 'name' => 'Asante Akim South', 'region_id' => 1],
			[ 'name' => 'Amansie West', 'region_id' => 1],
			[ 'name' => 'K. M. A.', 'region_id' => 1],
			[ 'name' => 'Ejura Sekyedumase', 'region_id' => 1],
			[ 'name' => 'Sekyere West', 'region_id' => 1],
			[ 'name' => 'Sekyere East', 'region_id' => 1],
			[ 'name' => 'Afigya Sekyere', 'region_id' => 1],
			[ 'name' => 'Ahafo Ano North', 'region_id' => 1],
			[ 'name' => 'Ahafo Ano South', 'region_id' => 1],
			[ 'name' => 'Atwima Mponua', 'region_id' => 1],
			[ 'name' => 'Sunyani', 'region_id' => 2],
			[ 'name' => 'Asutifi', 'region_id' => 2],
			[ 'name' => 'Asunafo North', 'region_id' => 2],
			[ 'name' => 'Asunafo South', 'region_id' => 2],
			[ 'name' => 'Jaman North', 'region_id' => 2],
			[ 'name' => 'Jaman South', 'region_id' => 2],
			[ 'name' => 'Kintampo North', 'region_id' => 2],
			[ 'name' => 'Kintampo South', 'region_id' => 2],
			[ 'name' => 'Atebubu - Amantin', 'region_id' => 2],
			[ 'name' => 'Pru', 'region_id' => 2],
			[ 'name' => 'Tain', 'region_id' => 2],
			[ 'name' => 'Wenchi', 'region_id' => 2],
			[ 'name' => 'Dormaa', 'region_id' => 2],
			[ 'name' => 'Berekum', 'region_id' => 2],
			[ 'name' => 'Tano North', 'region_id' => 2],
			[ 'name' => 'Tano South', 'region_id' => 2],
			[ 'name' => 'Sene', 'region_id' => 2],
			[ 'name' => 'Nkoranza', 'region_id' => 2],
			[ 'name' => 'Techiman', 'region_id' => 2],
			[ 'name' => 'Upper Denkyira', 'region_id' => 3],
			[ 'name' => 'Twifo-Herman/L. Denkyira', 'region_id' => 3],
			[ 'name' => 'Gomoa', 'region_id' => 3],
			[ 'name' => 'Cape Coast', 'region_id' => 3],
			[ 'name' => 'Agona', 'region_id' => 3],
			[ 'name' => 'Assin South', 'region_id' => 3],
			[ 'name' => 'Assin North', 'region_id' => 3],
			[ 'name' => 'Abura-Asebu-Kwamankesi', 'region_id' => 3],
			[ 'name' => 'Asikuma-Odoben-Brakwa', 'region_id' => 3],
			[ 'name' => 'Mfantsiman', 'region_id' => 3],
			[ 'name' => 'Komenda-Edina-Eguafo-Abirem', 'region_id' => 3],
			[ 'name' => 'Ajumako-Esiam-Enyan', 'region_id' => 3],
			[ 'name' => 'Awutu-Efutu-Senya', 'region_id' => 3],
			[ 'name' => 'Birim South', 'region_id' => 4],
			[ 'name' => 'West Akim', 'region_id' => 4],
			[ 'name' => 'Birim North', 'region_id' => 4],
			[ 'name' => 'Kwahu West', 'region_id' => 4],
			[ 'name' => 'Kwahu South', 'region_id' => 4],
			[ 'name' => 'Fanteakwa', 'region_id' => 4],
			[ 'name' => 'Afram Plains', 'region_id' => 4],
			[ 'name' => 'Asuogyaman', 'region_id' => 4],
			[ 'name' => 'Manya Krobo', 'region_id' => 4],
			[ 'name' => 'Suhum Kraboa Coaltar', 'region_id' => 4],
			[ 'name' => 'Akuapim South', 'region_id' => 4],
			[ 'name' => 'Akuapim North', 'region_id' => 4],
			[ 'name' => 'New Juaben', 'region_id' => 4],
			[ 'name' => 'Yilo Krobo', 'region_id' => 4],
			[ 'name' => 'East Akim', 'region_id' => 4],
			[ 'name' => 'Atiwa', 'region_id' => 4],
			[ 'name' => 'Kwaebibirem', 'region_id' => 4],
			[ 'name' => 'Tema', 'region_id' => 5],
			[ 'name' => 'Ga East', 'region_id' => 5],
			[ 'name' => 'Ga West', 'region_id' => 5],
			[ 'name' => 'Dangme West', 'region_id' => 5],
			[ 'name' => 'Dangme East', 'region_id' => 5],
			[ 'name' => 'AMA', 'region_id' => 5],
			[ 'name' => 'Bole', 'region_id' => 6],
			[ 'name' => 'Bunkpurugu/Yunyoo', 'region_id' => 6],
			[ 'name' => 'Savelugu/Nanton', 'region_id' => 6],
			[ 'name' => 'Sawla/Tuna/Kalba', 'region_id' => 6],
			[ 'name' => 'Tamale Metro', 'region_id' => 6],
			[ 'name' => 'Tolon/Kumbungu', 'region_id' => 6],
			[ 'name' => 'West Gonja', 'region_id' => 6],
			[ 'name' => 'West Mamprusi', 'region_id' => 6],
			[ 'name' => 'Yendi', 'region_id' => 6],
			[ 'name' => 'Zabzugu/Tatale', 'region_id' => 6],
			[ 'name' => 'Central Gonja', 'region_id' => 6],
			[ 'name' => 'East Gonja', 'region_id' => 6],
			[ 'name' => 'East Mamprusi', 'region_id' => 6],
			[ 'name' => 'Gushiegu', 'region_id' => 6],
			[ 'name' => 'Karaga', 'region_id' => 6],
			[ 'name' => 'Nanumba North', 'region_id' => 6],
			[ 'name' => 'Nanumba South', 'region_id' => 6],
			[ 'name' => 'Saboba/Cheriponi', 'region_id' => 6],
			[ 'name' => 'North Tongu', 'region_id' => 7],
			[ 'name' => 'South Tongu', 'region_id' => 7],
			[ 'name' => 'Nkwanta', 'region_id' => 7],
			[ 'name' => 'Krachi West', 'region_id' => 7],
			[ 'name' => 'Krachi East', 'region_id' => 7],
			[ 'name' => 'Ho', 'region_id' => 7],
			[ 'name' => 'Adaklu Anyigbe', 'region_id' => 7],
			[ 'name' => 'Akatsi', 'region_id' => 7],
			[ 'name' => 'Keta', 'region_id' => 7],
			[ 'name' => 'Ketu', 'region_id' => 7],
			[ 'name' => 'North Dayi (Kpando)', 'region_id' => 7],
			[ 'name' => 'South Dayi', 'region_id' => 7],
			[ 'name' => 'Hohoe', 'region_id' => 7],
			[ 'name' => 'Jasikan', 'region_id' => 7],
			[ 'name' => 'Kadjebi', 'region_id' => 7],
			[ 'name' => 'Wa West', 'region_id' => 8],
			[ 'name' => 'Wa East', 'region_id' => 8],
			[ 'name' => 'Wa Municipal', 'region_id' => 8],
			[ 'name' => 'Lawra', 'region_id' => 8],
			[ 'name' => 'Sisala East', 'region_id' => 8],
			[ 'name' => 'Sisala West', 'region_id' => 8],
			[ 'name' => 'Jirapa-Lambussie', 'region_id' => 8],
			[ 'name' => 'Nadowli', 'region_id' => 8],
			[ 'name' => 'BUILSA', 'region_id' => 9],
			[ 'name' => 'KASSENA NANKANA', 'region_id' => 9],
			[ 'name' => 'BOLGA', 'region_id' => 9],
			[ 'name' => 'BAWKU MUNICIPAL', 'region_id' => 9],
			[ 'name' => 'BAWKU WEST', 'region_id' => 9],
			[ 'name' => 'BONGO', 'region_id' => 9],
			[ 'name' => 'GARU TEMPANE', 'region_id' => 9],
			[ 'name' => 'TALENSI NABDAM', 'region_id' => 9],
			[ 'name' => 'Shama Ahanta    East', 'region_id' => 10],
			[ 'name' => 'West Ahanta', 'region_id' => 10],
			[ 'name' => 'Sefwi-Wiaso', 'region_id' => 10],
			[ 'name' => 'Bia', 'region_id' => 10],
			[ 'name' => 'Juabeso', 'region_id' => 10],
			[ 'name' => 'Mporhor Wassa East', 'region_id' => 10],
			[ 'name' => 'Wassa West', 'region_id' => 10],
			[ 'name' => 'East Nzema', 'region_id' => 10],
			[ 'name' => 'Jomoro', 'region_id' => 10],
			[ 'name' => 'Amenfi East', 'region_id' => 10],
			[ 'name' => 'Amenfi West (Wassa Amenfi)', 'region_id' => 10],
			[ 'name' => 'Aowin - Suaman', 'region_id' => 10],
			[ 'name' => 'Bibiani - Anhwiaso - Bekwai', 'region_id' => 10],
        ]);
    }
}
